// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3B7kTciunQXCWV_T24HoOxU6dcJ_reTQ',
    appId: '1:172486005214:android:47a4984026842a042f8d4f',
    messagingSenderId: '172486005214',
    projectId: 'sparkle-wrench',
    storageBucket: 'sparkle-wrench.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzR8K8EXx2xPvUv-YFnAZbynGYS_laqVg',
    appId: '1:172486005214:ios:935add98aa99f9382f8d4f',
    messagingSenderId: '172486005214',
    projectId: 'sparkle-wrench',
    storageBucket: 'sparkle-wrench.appspot.com',
    iosClientId: '172486005214-ucg5g9m99s62h5bu07j3p1puen9bge9u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkleWrench',
  );
}
